# Generated by Django 4.2.7 on 2023-12-19 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Todo name must contain at least 3 characters"
                            )
                        ],
                    ),
                ),
                ("description", models.TextField()),
                ("deadline", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
